name: Supabase Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DEPLOYMENT_CHANNEL: "live"
  PUBLIC_CLIENT_VARIABLES: ${{ vars.PUBLIC_CLIENT_VARIABLES }}
  VITE_APP_SUPABASE_KEY: ${{ secrets.VITE_APP_SUPABASE_KEY }}


jobs:
  run-front-test:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm test
